export const Routes = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  SIGN_IN: '/signIn',
  SIGN_UP: '/signUp',
  POST: '/post',
  POST_NEW: '/post/new',
  POST_EDIT: '/post/edit',
  ADD_ADMIN: '/addAdmin',
  EMAIL_CONFIRMATION: '/confirmEmail',
  EMAIL_ACTION: '/emailAction',
  COOKIE_POLICY: '/cookiePolicy',
  CHANGE_PASSWORD: '/changePassword',
};
